---
title: "SUMS Primary Analysis - Surrogate 5"
output: html_document
date: "2026-09-23"
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

#Load packages
library(gdata)
library(flextable)

#Load bootstrap function
setwd("../code/Bootstrap")
source("bootstrap_functions.R")


#function to prepare data for analysis
prep_data <- function (finaldata_primary) {
  
  finaldata_primary <- finaldata_primary %>%
  #exclude trials with no unscreened control arm
  filter(comparator_other_screening=="Not applicable") %>%
  # calculate weights (inverse variance 1/log(v))
  mutate(weight_var = 1/vi_m) %>%
  #only keep trials with available surrogate estimate
  filter(!is.na(yi_s)) %>%
  #count trials in analysis
  mutate(N_trials=n_distinct(trial_acro_sm))
  
  return(finaldata_primary)
}


#Create results table for surrogate 1
results_surrogate_5 <- data.frame(Cancer=character(),
                                  Surrogate=character(),
                                  Analysis=character(),
                                  Ntrials=numeric(),
                                  Intercept=numeric(),
                                  Intercept_lb_ci=numeric(),
                                  Intercept_ub_ci=numeric(),
                                  Slope=numeric(),
                                  Slope_lb_ci=numeric(),
                                  Slope_ub_ci=numeric(),
                                  Correlation=numeric(),
                                  Correlation_lb_ci=numeric(),
                                  Correlation_ub_ci=numeric(),
                                  Rsquared=numeric(),
                                  Rsquared_lb_ci=numeric(),
                                  Rsquared_ub_ci=numeric()
                                  )

#function to print cancer-specific results
print_results <- function(results_surrogate_5, cancer) {
  results_surrogate_5 %>%
    filter(Cancer == cancer) %>%
    mutate(Slope_lb_ci = ifelse(Slope_lb_ci == "-99999", "-Inf", Slope_lb_ci)) %>%
    mutate(Slope_ub_ci = ifelse(Slope_ub_ci == "99999", "Inf", Slope_ub_ci)) %>%
    flextable() %>%
    set_header_labels(
      Ntrials = "N trials",
      Intercept_lb_ci = "Intercept 95% CI; lower",
      Intercept_ub_ci = "Intercept 95% CI; upper",
      Slope_lb_ci = "Slope 95% CI; lower",
      Slope_ub_ci = "Slope 95% CI; upper",
      Correlation_lb_ci = "Correlation 95% CI; lower",
      Correlation_ub_ci = "Correlation 95% CI; upper",
      Rsquared = "R-squared",
      Rsquared_lb_ci = "R-squared 95% CI; lower",
      Rsquared_ub_ci = "R-squared 95% CI; upper"
    ) %>%
    autofit()
}

#function for cancer-specific plots
plot_cancer <- function(finaldata_primary_5, cancer, plottitle){
    
  plot_cancer <- ggplot(finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), label=trial_acro_sm, weight=weight_var)) +
  stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
    geom_point(aes(size = weight_var), shape = 16, colour="darkslateblue") +
    #geom_abline(intercept=0, slope=1, linetype=2)+
    geom_hline(yintercept = 1, linetype=3)+
    #geom_vline(xintercept = 1, linetype=3)+
    labs(x="% of target cancers that are screen-detected", y="RR Mortality", title=plottitle)+
    scale_x_continuous(limits=c(0,1))+
    scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
    geom_text(hjust=-0.05, vjust=-0.5)+
    theme_bw() +
    theme(legend.position = "none",plot.caption=element_text(hjust=0), aspect.ratio = 1)

  return(plot_cancer)
}


```

# Primary analysis

## Ovarian 

```{r ovarian, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Ovarian.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)


finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Ovarian", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Ovarian","All timepoints")

## BLUE + ORANGE // no earlier timepoints


##PINKS
#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Ovarian", "5. Proportion of target cancers that are screen-detected", "Same timepoint as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Ovarian", "Same timepoint as mortality")

# print results table for cancer
print_results(results_surrogate_5, "Ovarian")

```


## Occult

```{r occult, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Occult.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
add_row(analysis(finaldata_primary_5, "Occult cancer", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Occult cancer","All timepoints")



## BLUE + ORANGE // no earlier timepoints


##PINKS
#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Occult cancer", "5. Proportion of target cancers that are screen-detected", "Same timepoint as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Occult cancer", "Same timepoint as mortality")

# print results table for cancer
print_results(results_surrogate_5, "Occult cancer") 
```

## Lung

```{r lung, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Lung.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Lung", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Lung","All timepoints")

##BLUE/ORAGNES
finaldata_primary_5_earlier <- finaldata_primary_5 %>%
  filter(trial_acro_sm == "DLCST" |
           trial_acro_sm == "ITALUNG" |
           trial_acro_sm == "LUSI" |
            trial_acro_sm == "MILD") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5_earlier, "Lung", "5. Proportion of target cancers that are screen-detected", "Earlier than mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5_earlier,"Lung", "Earlier than mortality")


##PINKS
finaldata_primary_5_same <- finaldata_primary_5 %>%
  filter(
           trial_acro_sm == "Mayo Lung Project" |
           trial_acro_sm == "NELSON" |
            trial_acro_sm == "PLCO (Lung)"|
            trial_acro_sm == "UKLS" ) %>%
  prep_data()


#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5_same, "Lung", "5. Proportion of target cancers that are screen-detected", "Same timepoint as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5_same,"Lung", "Same timepoint as mortality")

# print results table for cancer
print_results(results_surrogate_5, "Lung")

```


## Breast

```{r breast, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Breast.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Breast", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Breast","All timepoints")


## BLUE + ORANGE
# finaldata_primary_5_earlier <- finaldata_primary_5 %>%
#   filter(trial_acro_sm == "Gothenburg Breast" |
#            trial_acro_sm == "HIP" |
#            trial_acro_sm == "Mumbai Breast Cervix") %>%
#   prep_data()
# 
# #Analysis (see function in Allcancer_functions.R)
# results_surrogate_5 <- results_surrogate_5 %>%
#   add_row(analysis(finaldata_primary_5_earlier, "Breast", "5. Proportion of target cancers that are screen-detected", "Earlier than mortality", bootstrap_trial))
# 
#   
# # bubble plot
# plot_cancer(finaldata_primary_5_earlier,"Breast", "Earlier than mortality")


##PINKS
finaldata_primary_5_same <- finaldata_primary_5 %>%
  filter(trial_acro_sm != "HIP") %>%
  filter(trial_acro_sm != "Mumbai Breast Cervix") %>%
  prep_data()


#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5_same, "Breast", "5. Proportion of target cancers that are screen-detected", "Same timepoint as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5_same,"Breast", "Same timepoint as mortality")

# print results table for cancer
print_results(results_surrogate_5, "Breast")

```

## Bowel

```{r bowel, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Bowel.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Bowel", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Bowel","All timepoints")



## BLUE + ORANGE
finaldata_primary_5_earlier <- finaldata_primary_5 %>%
  filter(trial_acro_sm == "NORCCAP" |
           trial_acro_sm == "Telemark Polyp I" |
           trial_acro_sm == "SCORE") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5_earlier, "Bowel", "5. Proportion of target cancers that are screen-detected", "Earlier than mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5_earlier,"Bowel", "Earlier than mortality")


##PINKS
finaldata_primary_5_same <- finaldata_primary_5 %>%
  filter(trial_acro_sm != "NORCCAP" &
           trial_acro_sm != "Telemark Polyp I" &
           trial_acro_sm != "SCORE") %>%
  prep_data()


#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5_same, "Bowel", "5. Proportion of target cancers that are screen-detected", "Same timepoint as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5_same,"Bowel", "Same timepoint as mortality")

# print results table for cancer
print_results(results_surrogate_5, "Bowel")
```

## Prostate

```{r prostate, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Prostate.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Prostate", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))


# bubble plot
plot_cancer(finaldata_primary_5,"Prostate","All timepoints")

# print results table for cancer
print_results(results_surrogate_5, "Prostate")

## BLUE + ORANGE
# not enough trials

##PINKS
#not enough trials
```


## All cancers
```{r all, echo=FALSE, warning=FALSE}

#Load cancer-specific data
setwd("../code/Estimates")
source("Ovarian.R")
ovarian <- finaldata_primary_5 %>%
  mutate(cancer="Ovarian")

setwd("../code/Estimates")
source("Cervical.R")
cervical <- finaldata_primary_5 %>%
  mutate(cancer="Cervical") %>%
  #differentiate Mumbai Breast and Cervix
  mutate(trial_acro_sm=ifelse(trial_acro_sm=="Mumbai Breast Cervix","Mumbai Cervix",trial_acro_sm))

setwd("../code/Estimates")
source("Liver.R")
liver <- finaldata_primary_5 %>%
  mutate(cancer="Liver")

setwd("../code/Estimates")
source("Nasopharyngeal.R")
nasopharyngeal <- finaldata_primary_5 %>%
  mutate(cancer="Nasopharyngeal")

setwd("../code/Estimates")
source("Oral.R")
oral <- finaldata_primary_5 %>%
  mutate(cancer="Oral")

setwd("../code/Estimates")
source("Occult.R")
occult <- finaldata_primary_5 %>%
  mutate(cancer="Multiple")

setwd("../code/Estimates")
source("Lung.R")
lung <- finaldata_primary_5 %>%
  mutate(cancer="Lung")

setwd("../code/Estimates")
source("Prostate.R")
prostate <- finaldata_primary_5 %>%
  mutate(cancer="Prostate")

setwd("../code/Estimates")
source("Breast.R")
breast <- finaldata_primary_5 %>%
  mutate(cancer="Breast") %>%
    #differentiate Mumbai Breast and Cervix
    mutate(trial_acro_sm=ifelse(trial_acro_sm=="Mumbai Breast Cervix","Mumbai Breast",trial_acro_sm))

setwd("../code/Estimates")
source("Bowel.R")
bowel <- finaldata_primary_5 %>%
  mutate(cancer="Bowel")

gdata::keep(
  ovarian,
  cervical,
  liver,
  nasopharyngeal,
  oral,
  occult,
  lung,
  prostate,
  breast,
  bowel,
  results_surrogate_5,
  analysis,
  prep_data,
  min_N_trials,
  bootstrap_trial,
  sure = T
)

all_finaldata_primary_5 <- bind_rows(ovarian,
                                     cervical,
                                     liver,
                                     nasopharyngeal,
                                     oral,
                                     occult,
                                     lung,
                                     prostate,
                                     breast,
                                     bowel)


all_finaldata_primary_5 <- prep_data(all_finaldata_primary_5) 
##write_csv(all_finaldata_primary_5,"julia-data-5.csv")

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(all_finaldata_primary_5, "All", "5. Proportion of target cancers that are screen-detected", "All timepoints", bootstrap_trial))

# bubble plot
ggplot(all_finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
  stat_smooth(method="lm", colour=NA, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  geom_abline(data=results_surrogate_5, aes(intercept = Intercept[Cancer=="All"], slope = Slope[Cancer=="All"])) +
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
  scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="All timepoints")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 


# bubble plot, increased size for pub
fig4<-ggplot(all_finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
  stat_smooth(method="lm", colour=NA, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  geom_abline(data=results_surrogate_5, aes(intercept = Intercept[Cancer=="All"], slope = Slope[Cancer=="All"])) +
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  scale_y_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,2,5)) +
  scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="All timepoints")+
    theme_bw() +
    theme(
        plot.caption = element_text(hjust = 0),
        aspect.ratio = 1,
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 14)
    ) +
    guides(
        size = FALSE,
        colour = guide_legend(
            override.aes = list(size = 5)
        )
    )+
    scale_colour_discrete(name = "Cancer type")



ggsave("../code/plots/fig4.png", plot = fig4,
       width = 6, height = 6, units = "in", dpi = 300)
 
ggsave("../code/plots/fig4.pdf", plot = fig4,
       width = 6, height = 6, units = "in")




## BLUE + ORANGE
all_finaldata_primary_5_earlier <- all_finaldata_primary_5 %>%
  #Bowel
   filter(trial_acro_sm == "NORCCAP" |
           trial_acro_sm == "Telemark Polyp I" |
            trial_acro_sm == "SCORE" |
  #Breast
           trial_acro_sm == "HIP" |
           trial_acro_sm == "Mumbai Breast" |
  #cervical
    #no trials
  #Liver
    #no trials
  #Lung
           trial_acro_sm == "DLCST" |
           trial_acro_sm == "ITALUNG" |
           trial_acro_sm == "LUSI" |
            trial_acro_sm == "MILD" )  %>%
  #NPC
    # no trials
  #Oral
    #no trials
  #Ovarian
    #no trials
  #Prostate
          ##    trial_acro_sm == "PLCO (Prostate)") %>%         
 prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(all_finaldata_primary_5_earlier, "All", "5. Proportion of target cancers that are screen-detected", "Earlier than morality", bootstrap_trial))

# bubble plot
ggplot(all_finaldata_primary_5_earlier, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
    stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
  scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="Earlier than mortality")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 

##PINKS
all_finaldata_primary_5_same <- all_finaldata_primary_5 %>%
   #Bowel
   filter(trial_acro_sm != "NORCCAP" &
           trial_acro_sm != "Telemark Polyp I" &
            trial_acro_sm != "SCORE" &
  #Breast
           trial_acro_sm != "HIP" &
           trial_acro_sm != "Mumbai Breast Cervix" &
  #cervical
    #no trials
  #Liver
    #no trials
  #Lung
           trial_acro_sm != "DLCST" &
           trial_acro_sm != "ITALUNG" &
           trial_acro_sm != "LUSI" &
            trial_acro_sm != "MILD" &
  #NPC
    # no trials
  #Oral
    #no trials
  #Ovarian
    #no trials
  #Prostate
    trial_acro_sm != "PLCO (Prostate)") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(all_finaldata_primary_5_same, "All", "5. Proportion of target cancers that are screen-detected", "Same timepoint as morality", bootstrap_trial))

# bubble plot
ggplot(all_finaldata_primary_5_same, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
    stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
    scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
    scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="Same timepoint as mortality")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 


# print results table for all cancers & all timepoints
results_surrogate_5 %>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()

```

# Additional plots

```{r plots, echo=FALSE, warning=FALSE}

# Surrogate  - by cancer grid
all_finaldata_primary_5 <- all_finaldata_primary_5 %>%
  # remove cancer with <3 trials available
  filter(cancer!="Liver") %>%
  filter(cancer!="Nasopharyngeal") %>%
  filter(cancer!="Oral") %>%
  filter(cancer!="Cervical") %>%
  filter(cancer!="Prostate")

ggplot(all_finaldata_primary_5, aes( x = yi_s, y = exp(yi_m), label=trial_acro_sm, weight=weight_var)) +
  #remove ovarian cancer 95% CIs to reflect results (taking into account common control groups in UKCTOCS)
  stat_smooth(data=subset(all_finaldata_primary_5, cancer!="Ovarian"), method="lm", colour="black", linewidth=0.6, fullrange=T)+
  stat_smooth(data=subset(all_finaldata_primary_5, cancer=="Ovarian"), method="lm", colour="black", linewidth=0.6, fullrange=T, se=F)+
  geom_point(aes(size = weight_var), shape = 16, colour="darkslateblue") +
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", title="All timepoints")+
    scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
  facet_wrap(~cancer, nrow=2)+
  theme_bw() +
  theme(legend.position = "none",plot.caption=element_text(hjust=0), aspect.ratio = 1) 


```
