---
title: "SUMS Sensitivity Analysis - Timepoints - Surrogate 5"
output: html_document
date: "2024-05-09"
---

Sensitivity analysis restricting to timepoints:
- end of intervention
- end of intervention and same time as mortality

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

#Load packages
library(gdata)
library(flextable)

#Load bootstrap function
setwd("../code/Bootstrap")
source("bootstrap_functions.R")


#function to prepare data for analysis
prep_data <- function (finaldata_primary) {
  
  finaldata_primary <- finaldata_primary %>%
  #exclude trials with no unscreened control arm
  filter(comparator_other_screening=="Not applicable") %>%
  # calculate weights (inverse variance 1/log(v))
  mutate(weight_var = 1/vi_m) %>%
  #only keep trials with available surrogate estimate
  filter(!is.na(yi_s)) %>%
  #count trials in analysis
  mutate(N_trials=n_distinct(trial_acro_sm))
  
  return(finaldata_primary)
}


#Create results table for surrogate 1
results_surrogate_5 <- data.frame(Cancer=character(),
                                  Surrogate=character(),
                                  Analysis=character(),
                                  Ntrials=numeric(),
                                  Intercept=numeric(),
                                  Intercept_lb_ci=numeric(),
                                  Intercept_ub_ci=numeric(),
                                  Slope=numeric(),
                                  Slope_lb_ci=numeric(),
                                  Slope_ub_ci=numeric(),
                                  Correlation=numeric(),
                                  Correlation_lb_ci=numeric(),
                                  Correlation_ub_ci=numeric(),
                                  Rsquared=numeric(),
                                  Rsquared_lb_ci=numeric(),
                                  Rsquared_ub_ci=numeric()
                                  )

#function to print cancer-specific results
print_results <- function(results_surrogate_5, cancer) {
  results_surrogate_5 %>%
    filter(Cancer == cancer) %>%
    mutate(Slope_lb_ci = ifelse(Slope_lb_ci == "-99999", "-Inf", Slope_lb_ci)) %>%
    mutate(Slope_ub_ci = ifelse(Slope_ub_ci == "99999", "Inf", Slope_ub_ci)) %>%
    flextable() %>%
    set_header_labels(
      Ntrials = "N trials",
      Intercept_lb_ci = "Intercept 95% CI; lower",
      Intercept_ub_ci = "Intercept 95% CI; upper",
      Slope_lb_ci = "Slope 95% CI; lower",
      Slope_ub_ci = "Slope 95% CI; upper",
      Correlation_lb_ci = "Correlation 95% CI; lower",
      Correlation_ub_ci = "Correlation 95% CI; upper",
      Rsquared = "R-squared",
      Rsquared_lb_ci = "R-squared 95% CI; lower",
      Rsquared_ub_ci = "R-squared 95% CI; upper"
    ) %>%
    autofit()
}

#function for cancer-specific plots
plot_cancer <- function(finaldata_primary_5, cancer, plottitle){
    
  plot_cancer <- ggplot(finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), label=trial_acro_sm, weight=weight_var)) +
  stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
    geom_point(aes(size = weight_var), shape = 16, colour="darkslateblue") +
    #geom_abline(intercept=0, slope=1, linetype=2)+
    geom_hline(yintercept = 1, linetype=3)+
    #geom_vline(xintercept = 1, linetype=3)+
    labs(x="% of target cancers that are screen-detected", y="RR Mortality", title=plottitle)+
    scale_x_continuous(limits=c(0,1))+
    scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
    geom_text(hjust=-0.05, vjust=-0.5)+
    theme_bw() +
    theme(legend.position = "none",plot.caption=element_text(hjust=0), aspect.ratio = 1)

  return(plot_cancer)
}


```

# Primary analysis

## Lung

```{r lung, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Lung.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- finaldata_primary_5 %>%
  filter(trial_acro_sm=="DLCST" |
  trial_acro_sm=="LUSI" |
  trial_acro_sm=="Mayo Lung Project") %>%
  prep_data()

## BLUE AND DARK PINK (End of intervention)
#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Lung", "5. Proportion of target cancers that are screen-detected", "End of intervention", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Lung", "End of intervention")


# print results table for cancer
print_results(results_surrogate_5, "Lung")

```


## Breast

```{r breast, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Breast.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)


## BLUE AND DARK PINK (End of intervention)
finaldata_primary_5 <- finaldata_primary_5 %>%
  filter(trial_acro_sm != "Trivandrum Breast") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Breast", "5. Proportion of target cancers that are screen-detected", "End of intervention", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Breast", "End of intervention")

## DARK PINK (End of intervention + same time as mortality)
finaldata_primary_5 <- finaldata_primary_5 %>%
  filter(trial_acro_sm != "Trivandrum Breast") %>%
    filter(trial_acro_sm != "HIP") %>%
    filter(trial_acro_sm != "Mumbai Breast Cervix") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Breast", "5. Proportion of target cancers that are screen-detected", "End of intervention and same time as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Breast", "End of intervention and same time as mortality")


# print results table for cancer
print_results(results_surrogate_5, "Breast")

```

## Bowel

```{r bowel, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Bowel.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)


## DARK PINK (End of intervention + same time as mortality)
finaldata_primary_5 <- finaldata_primary_5 %>%
  filter(trial_acro_sm == "Finnish RHS CRC" |
           trial_acro_sm == "Funen" |
           trial_acro_sm == "Minnesota" |
           trial_acro_sm == "Nottingham" ) %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Bowel", "5. Proportion of target cancers that are screen-detected", "End of intervention and same time as mortality", bootstrap_trial))
  
# bubble plot
plot_cancer(finaldata_primary_5,"Bowel", "End of intervention and same time as mortality")


# print results table for cancer
print_results(results_surrogate_5, "Bowel")

```

## Prostate

```{r prostate, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Prostate.R")

gdata::keep(
  finaldata_primary_5,
  results_surrogate_5,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_5 <- prep_data(finaldata_primary_5)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(finaldata_primary_5, "Prostate", "5. Proportion of target cancers that are screen-detected", "End of intervention", bootstrap_trial))


# bubble plot
plot_cancer(finaldata_primary_5,"Prostate","End of intervention")

# print results table for cancer
print_results(results_surrogate_5, "Prostate")

## BLUE + ORANGE
# not enough trials

##PINKS
#not enough trials
```


## All cancers
```{r all, echo=FALSE, warning=FALSE}

#Load cancer-specific data
setwd("../code/Estimates")
source("Ovarian.R")
ovarian <- finaldata_primary_5 %>%
  mutate(cancer="Ovarian")

setwd("../code/Estimates")
source("Cervical.R")
cervical <- finaldata_primary_5 %>%
  mutate(cancer="Cervical") %>%
  #differentiate Mumbai Breast and Cervix
  mutate(trial_acro_sm=ifelse(trial_acro_sm=="Mumbai Breast Cervix","Mumbai Cervix",trial_acro_sm))

setwd("../code/Estimates")
source("Liver.R")
liver <- finaldata_primary_5 %>%
  mutate(cancer="Liver")

setwd("../code/Estimates")
source("Nasopharyngeal.R")
nasopharyngeal <- finaldata_primary_5 %>%
  mutate(cancer="Nasopharyngeal")

setwd("../code/Estimates")
source("Oral.R")
oral <- finaldata_primary_5 %>%
  mutate(cancer="Oral")

setwd("../code/Estimates")
source("Occult.R")
occult <- finaldata_primary_5 %>%
  mutate(cancer="Occult")

setwd("../code/Estimates")
source("Lung.R")
lung <- finaldata_primary_5 %>%
  mutate(cancer="Lung")

setwd("../code/Estimates")
source("Prostate.R")
prostate <- finaldata_primary_5 %>%
  mutate(cancer="Prostate")

setwd("../code/Estimates")
source("Breast.R")
breast <- finaldata_primary_5 %>%
  mutate(cancer="Breast") %>%
    #differentiate Mumbai Breast and Cervix
    mutate(trial_acro_sm=ifelse(trial_acro_sm=="Mumbai Breast Cervix","Mumbai Breast",trial_acro_sm))

setwd("../code/Estimates")
source("Bowel.R")
bowel <- finaldata_primary_5 %>%
  mutate(cancer="Bowel")

gdata::keep(
  ovarian,
  cervical,
  liver,
  nasopharyngeal,
  oral,
  occult,
  lung,
  prostate,
  breast,
  bowel,
  results_surrogate_5,
  analysis,
  prep_data,
  min_N_trials,
  bootstrap_trial,
  sure = T
)

all_finaldata_primary_5 <- bind_rows(ovarian,
                                     cervical,
                                     liver,
                                     nasopharyngeal,
                                     oral,
                                     occult,
                                     lung,
                                     prostate,
                                     breast,
                                     bowel)


## BLUE AND DARK PINK (End of intervention)
all_finaldata_primary_5 <- all_finaldata_primary_5 %>%
  #Bowel
  filter(
    trial_acro_sm == "Finnish RHS CRC" |
           trial_acro_sm == "Funen" |
           trial_acro_sm == "Minnesota" |
           trial_acro_sm == "Nottingham" |
      #Breast
      trial_acro_sm == "Edinburgh" |
      trial_acro_sm == "Gothenburg Breast" |
      trial_acro_sm == "HIP" |
      trial_acro_sm == "MMST I" |
      trial_acro_sm == "Mumbai Breast" |
      trial_acro_sm == "Shanghai Breast" |
      trial_acro_sm == "Stockholm Breast" |
      trial_acro_sm == "Two-County" |
      trial_acro_sm == "UK Age" |
      #cervical
      #no trials
      #Liver
      trial_acro_sm == "Shanghai Liver" |
      #Lung
      trial_acro_sm == "DLCST" |
      trial_acro_sm == "LUSI" | 
      trial_acro_sm=="Mayo Lung Project" |
  #NPC
    # no trials
  #Oral
    trial_acro_sm == "Trivandrum Oral" |
  #Ovarian
    #no trials
  #Prostate
    trial_acro_sm == "ERSPC" |
    trial_acro_sm == "Norrkoping" |
    trial_acro_sm == "PLCO (Prostate)") %>%
  prep_data()

#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(all_finaldata_primary_5, "All", "5. Proportion of target cancers that are screen-detected", "End of intervention", bootstrap_trial))

# bubble plot
ggplot(all_finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
    stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
  scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="End of intervention")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 


## DARK PINK (End of intervention + same time as mortality)
all_finaldata_primary_5 <- all_finaldata_primary_5 %>%
  filter(trial_acro_sm!="HIP") %>%
  filter(trial_acro_sm!="Mumbai Breast") %>%
    filter(trial_acro_sm!="DLCST") %>%
    filter(trial_acro_sm!="LUSI") %>%
    filter(trial_acro_sm != "PLCO (Prostate)") %>%
  prep_data()


#Analysis (see function in Allcancer_functions.R)
results_surrogate_5 <- results_surrogate_5 %>%
  add_row(analysis(all_finaldata_primary_5, "All", "5. Proportion of target cancers that are screen-detected", "End of intervention and same time as mortality", bootstrap_trial))

# bubble plot
ggplot(all_finaldata_primary_5, aes(x = yi_s, y = exp(yi_m), weight=weight_var)) +
    stat_smooth(method="lm", colour="black", linewidth=0.6, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  #geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  #geom_vline(xintercept = 1, linetype=3)+
  scale_y_continuous(trans="log", limits = c(0.3,6), breaks=c(0.5,1,2,5)) +
  scale_x_continuous(limits=c(0,1))+
  labs(x="% of target cancers that are screen-detected", y="RR Mortality", colour="Cancer type", title="End of intervention and same time as mortality")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 


# print results table for all cancers & all timepoints
results_surrogate_5 %>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()

```


