---
title: "SUMS Sensitivity Analysis - Late-stage definition - Surrogate 1 "
output: html_document
date: "2024-03-19"
---

This sensitivity analysis is using stage III/IV as a consistent definition of late-stage cancer across cancer types.

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(gdata)
library(flextable)

#Load bootstrap function
setwd("../code/Bootstrap")
source("bootstrap_functions.R")


#function to prepare data for analysis
prep_data <- function (finaldata_primary) {
  
  finaldata_primary <- finaldata_primary %>%
  # calculate weights (inverse variance 1/log(v))
  mutate(weight_var = 1/vi_m) %>%
  #only keep trials with available surrogate estimate
  filter(!is.na(yi_s)) %>%
  #count trials in analysis
  mutate(N_trials=n_distinct(trial_acro_sm))
  
  return(finaldata_primary)
}


# create results table for surrogate 1
results_surrogate_1 <- data.frame(Cancer=character(),
                                  Surrogate=character(),
                                  Analysis=character(),
                                  Subrgoup=character(),
                                  Ntrials=numeric(),
                                  Intercept=numeric(),
                                  Intercept_lb_ci=numeric(),
                                  Intercept_ub_ci=numeric(),
                                  Slope=numeric(),
                                  Slope_lb_ci=numeric(),
                                  Slope_ub_ci=numeric(),
                                  Correlation=numeric(),
                                  Correlation_lb_ci=numeric(),
                                  Correlation_ub_ci=numeric(),
                                  Rsquared=numeric(),
                                  Rsquared_lb_ci=numeric(),
                                  Rsquared_ub_ci=numeric()
                                  )

#function to print cancer-specific results
print_results <- function(results_surrogate_1, cancer) {
results_surrogate_1 %>%
  filter(Cancer==cancer)%>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()
}

#function for cancer-specific plots
plot_cancer <- function(finaldata_primary_1, cancer){
    
  plot_cancer <- ggplot(finaldata_primary_1, aes(x = exp(yi_s), y = exp(yi_m), label=trial_acro_sm, weight=weight_var)) +
    stat_smooth(method="lm", colour=NA, fullrange=T)+
    geom_point(aes(size = weight_var), shape = 16, colour="darkslateblue") +
    geom_abline(intercept = results_surrogate_1$Intercept[results_surrogate_1$Cancer==cancer], slope = results_surrogate_1$Slope[results_surrogate_1$Cancer==cancer]) +
    geom_abline(intercept=0, slope=1, linetype=2)+
    geom_hline(yintercept = 1, linetype=3)+
    geom_vline(xintercept = 1, linetype=3)+
    labs(x="RR late stage incidence", y="RR Mortality")+
    scale_x_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2)) + 
    scale_y_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2)) +
    geom_text(hjust=-0.05, vjust=-0.5)+
    theme_bw() +
    theme(legend.position = "none",plot.caption=element_text(hjust=0), aspect.ratio = 1)

  return(plot_cancer)
}

```


## Ovarian 

```{r ovarian, echo=FALSE, warning=FALSE}

setwd("../code/Estimates/Stage III-IV")
source("Ovarian.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)


finaldata_primary_1 <- prep_data(finaldata_primary_1)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Ovarian", "1. Absolute incidence of late stage cancer", "Sensitivity", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Ovarian")
  
# bubble plot
plot_cancer(finaldata_primary_1,"Ovarian")

```



## Lung

```{r lung, echo=FALSE, warning=FALSE}
setwd("../code/Estimates/Stage III-IV")
source("Lung.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_1 <- prep_data(finaldata_primary_1)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Lung", "1. Absolute incidence of late stage cancer", "Sensitivity", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Lung")
  
# bubble plot
plot_cancer(finaldata_primary_1,"Lung")

```

## Breast

```{r breast, echo=FALSE, warning=FALSE}
setwd("../code/Estimates/Stage III-IV")
source("Breast.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  analysis,
  prep_data,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

finaldata_primary_1 <- prep_data(finaldata_primary_1)

#Analysis (see function in Allcancer_functions.R)
results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Breast", "1. Absolute incidence of late stage cancer", "Sensitivity", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Breast")
  
# bubble plot
plot_cancer(finaldata_primary_1,"Breast")

```




## All cancers
```{r all, echo=FALSE, warning=FALSE}

#Load cancer-specific data
setwd("../code/Estimates/Stage III-IV")
source("Ovarian.R")
ovarian <- finaldata_primary_1 %>%
  mutate(cancer="Ovarian")

setwd("../code/Estimates/Stage III-IV")
source("Liver.R")
liver <- finaldata_primary_1 %>%
  mutate(cancer="Liver")

setwd("../code/Estimates/Stage III-IV")
source("Nasopharyngeal.R")
nasopharyngeal <- finaldata_primary_1 %>%
  mutate(cancer="Nasopharyngeal")

setwd("../code/Estimates/Stage III-IV")
source("Oral.R")
oral <- finaldata_primary_1 %>%
  mutate(cancer="Oral")

setwd("../code/Estimates/Stage III-IV")
source("Occult.R")
occult <- finaldata_primary_1 %>%
  mutate(cancer="Occult")

setwd("../code/Estimates/Stage III-IV")
source("Lung.R")
lung <- finaldata_primary_1 %>%
  mutate(cancer="Lung")

setwd("../code/Estimates/Stage III-IV")
source("Prostate.R")
prostate <- finaldata_primary_1 %>%
  mutate(cancer="Prostate")

setwd("../code/Estimates/Stage III-IV")
source("Breast.R")
breast <- finaldata_primary_1 %>%
  mutate(cancer="Breast") %>%
    #differentiate Mumbai Breast and Cervix
    mutate(trial_acro_sm=ifelse(trial_acro_sm=="Mumbai Breast Cervix","Mumbai Breast",trial_acro_sm))

setwd("../code/Estimates/Stage III-IV")
source("Bowel.R")
bowel <- finaldata_primary_1 %>%
  mutate(cancer="Bowel")

gdata::keep(
  ovarian,
  liver,
  nasopharyngeal,
  oral,
  occult,
  lung,
  prostate,
  breast,
  bowel,
  results_surrogate_1,
  analysis,
  prep_data,
  min_N_trials,
  bootstrap_trial,
  sure = T
)

all_finaldata_primary_1 <- bind_rows(ovarian,
                                     liver,
                                     nasopharyngeal,
                                     oral,
                                     occult,
                                     lung,
                                     prostate,
                                     breast,
                                     bowel)


all_finaldata_primary_1 <- prep_data(all_finaldata_primary_1) 

#Analysis (see function in Allcancer_functions.R)
results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(all_finaldata_primary_1, "All", "1. Absolute incidence of late stage cancer", "Sensitivity", bootstrap_trial))

# print results table for all cancers
results_surrogate_1 %>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()

# bubble plot
ggplot(all_finaldata_primary_1, aes(x = exp(yi_s), y = exp(yi_m), weight=weight_var)) +
  stat_smooth(method="lm", colour=NA, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  geom_abline(data=results_surrogate_1, aes(intercept = Intercept[Cancer=="All"], slope = Slope[Cancer=="All"])) +
  geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  geom_vline(xintercept = 1, linetype=3)+
  scale_x_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2))+
  scale_y_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2))+
  labs(x="RR late stage incidence", y="RR Mortality")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0),  aspect.ratio = 1) +
  guides(size = FALSE) 
```


<!-- # Secondary Analysis -->

<!-- ## Cervical -->

<!-- ```{r cervical_2, echo=FALSE, warning=FALSE} -->
<!-- source("Cervical.R") -->
<!-- gdata::keep(finaldata_secondary_1, results_surrogate_1, analysis, sure=T) -->

<!-- #Weights -->
<!-- finaldata_secondary_1 <- finaldata_secondary_1 %>% -->
<!--   # inverse variance 1/log(v) -->
<!--   mutate(weight_var = 1/vi_m) -->



<!-- results_surrogate_1 <- results_surrogate_1 %>% -->
<!--   add_row(analysis(finaldata_secondary_1, "Cervical", "1. Absolute incidence of late stage cancer", "Secondary")) -->

<!-- # print results table for cancer -->
<!-- autofit(flextable(analysis(finaldata_secondary_1, "Cervical", "1. Absolute incidence of late stage cancer", "Secondary"))) -->

<!-- # bubble plot -->
<!-- ggplot(finaldata_secondary_1, aes(x = exp(yi_s), y = exp(yi_m),label=trial_acro_sm)) + -->
<!--   #scale_y_continuous(trans="exp")+ -->
<!--   geom_point(aes(size = weight_var, colour=subgroup_m),  shape = 16) + -->
<!--   #geom_errorbar(aes(ymin=exp(ci.lb_m), ymax=exp(ci.ub_m)), size=1, width=0.01, alpha=0.3)+ -->
<!--   #geom_errorbar(aes(xmin=exp(ci.lb_s), xmax=exp(ci.ub_s)), size=1, width=0.01, alpha=0.3)+ -->
<!--   geom_abline(data=results_surrogate_1, intercept = results_surrogate_1$Intercept[results_surrogate_1$Cancer=="Cervical" & results_surrogate_1$Analysis=="Secondary"], slope = results_surrogate_1$Slope[results_surrogate_1$Cancer=="Cervical"& results_surrogate_1$Analysis=="Secondary"]) + -->
<!--   geom_abline(intercept=0, slope=1, linetype=2)+ -->
<!--   geom_text(hjust=-0.05, vjust=1.5)+ -->
<!--   scale_x_continuous(trans="log", limits=c(-1, 1.4),  breaks=c(0.5,1,1.5))+ -->
<!--   scale_y_continuous(trans="log", limits=c(-1, 1.4), breaks=c(0.5,1,1.5))+ -->
<!--   labs(x="logRR late-stage incidence", y="logRR Mortality", colour="Subgroup")+ -->
<!--   theme_bw() + -->
<!--   guides(size = "none") -->
<!-- ``` -->

<!-- ## Prostate -->

<!-- ```{r prostate_2, echo=FALSE, warning=FALSE} -->
<!-- source("Prostate.R") -->
<!-- gdata::keep(finaldata_secondary_1, results_surrogate_1, analysis, sure=T) -->

<!-- #Weights -->
<!-- finaldata_secondary_1 <- finaldata_secondary_1 %>% -->
<!--   # inverse variance 1/log(v) -->
<!--   mutate(weight_var = 1/vi_m) -->



<!-- results_surrogate_1 <- results_surrogate_1 %>% -->
<!--   add_row(analysis(finaldata_secondary_1, "Prostate", "1. Absolute incidence of late stage cancer", "Secondary")) -->

<!-- # print results table for cancer -->
<!-- autofit(flextable(analysis(finaldata_secondary_1, "Prostate", "1. Absolute incidence of late stage cancer", "Secondary"))) -->

<!-- # bubble plot -->
<!-- ggplot(finaldata_secondary_1, aes(x = exp(yi_s), y = exp(yi_m),label=trial_acro_sm)) + -->
<!--   #scale_y_continuous(trans="exp")+ -->
<!--   geom_point(aes(size = weight_var, colour=subgroup_m),  shape = 16) + -->
<!--   #geom_errorbar(aes(ymin=exp(ci.lb_m), ymax=exp(ci.ub_m)), size=1, width=0.01, alpha=0.3)+ -->
<!--   #geom_errorbar(aes(xmin=exp(ci.lb_s), xmax=exp(ci.ub_s)), size=1, width=0.01, alpha=0.3)+ -->
<!--   geom_abline(data=results_surrogate_1, intercept = results_surrogate_1$Intercept[results_surrogate_1$Cancer=="Prostate" & results_surrogate_1$Analysis=="Secondary"], slope = results_surrogate_1$Slope[results_surrogate_1$Cancer=="Prostate"& results_surrogate_1$Analysis=="Secondary"]) + -->
<!--   geom_abline(intercept=0, slope=1, linetype=2)+ -->
<!--   geom_text(hjust=-0.05, vjust=1.5)+ -->
<!--   scale_x_continuous(trans="log", limits=c(-1, 1.4),  breaks=c(0.5,1,1.5))+ -->
<!--   scale_y_continuous(trans="log", limits=c(-1, 1.4), breaks=c(0.5,1,1.5))+ -->
<!--   labs(x="logRR late-stage incidence", y="logRR Mortality", colour="Subgroup")+ -->
<!--   theme_bw() + -->
<!--   guides(size = "none") -->
<!-- ``` -->

<!-- ## Breast -->

<!-- ```{r breast_2, echo=FALSE, warning=FALSE} -->
<!-- source("Breast.R") -->
<!-- gdata::keep(finaldata_secondary_1, results_surrogate_1, secondary_analysis, sure=T) -->

<!-- #Weights -->
<!-- finaldata_secondary_1 <- finaldata_secondary_1 %>% -->
<!--   # log(number of deaths) -->
<!--   mutate(weight_deaths = numerator_screening_m + numerator_comparator_m) %>% -->
<!--   # inverse variance 1/log(v) -->
<!--   mutate(weight_var = 1/vi_m) -->



<!-- results_surrogate_1 <- results_surrogate_1 %>% -->
<!--   add_row(secondary_analysis(finaldata_secondary_1, "Breast", "1. Absolute incidence of late stage cancer", "Secondary")) -->

<!-- # print results table for cancer -->
<!-- autofit(flextable(secondary_analysis(finaldata_secondary_1, "Breast", "1. Absolute incidence of late stage cancer", "Secondary"))) -->

<!-- # bubble plot -->
<!-- ggplot(finaldata_secondary_1, aes(x = exp(yi_s), y = exp(yi_m),label=trial_acro_sm)) + -->
<!--   #scale_y_continuous(trans="exp")+ -->
<!--   geom_point(aes(size = weight_var, colour=subgroup_m),  shape = 16) +  -->
<!--   #geom_errorbar(aes(ymin=exp(ci.lb_m), ymax=exp(ci.ub_m)), size=1, width=0.01, alpha=0.3)+ -->
<!--   #geom_errorbar(aes(xmin=exp(ci.lb_s), xmax=exp(ci.ub_s)), size=1, width=0.01, alpha=0.3)+ -->
<!--   geom_abline(data=results_surrogate_1, intercept = results_surrogate_1$Intercept[results_surrogate_1$Cancer=="Breast" & results_surrogate_1$Analysis=="Secondary"], slope = results_surrogate_1$Slope[results_surrogate_1$Cancer=="Breast"& results_surrogate_1$Analysis=="Secondary"]) + -->
<!--   geom_abline(intercept=0, slope=1, linetype=2)+ -->
<!--   geom_text(hjust=-0.05, vjust=1.5)+ -->
<!--   scale_x_continuous(trans="log", limits=c(-1, 1.4),  breaks=c(0.5,1,1.5))+ -->
<!--   scale_y_continuous(trans="log", limits=c(-1, 1.4), breaks=c(0.5,1,1.5))+ -->
<!--   labs(x="logRR late-stage incidence", y="logRR Mortality", colour="Subgroup")+ -->
<!--   theme_bw() +  -->
<!--   guides(size = "none")  -->
<!-- ``` -->


