---
title: "SUMS Subgroup Analysis - Earlier Follow-up - Surrogate 1"
output: html_document
date: "2025-01-14"
---

This is a subgroup analysis only including trials which the surrogate was measured before the mortality outcome.

```{r setup, include=FALSE} 
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

#Load packages
library(gdata)
library(flextable)

#Load bootstrap function
setwd("../code/Bootstrap")
source("bootstrap_functions.R")

#function to prepare data for analysis
prep_data <- function (finaldata_primary) {
  
  finaldata_primary <- finaldata_primary %>%
  # calculate weights (inverse variance 1/log(v))
  mutate(weight_var = 1/vi_m) %>%
  #only keep trials with available surrogate estimate
  filter(!is.na(yi_s)) %>%
  #count trials in analysis
  mutate(N_trials=n_distinct(trial_acro_sm))
  
  return(finaldata_primary)
}

# create results table for surrogate 1
results_surrogate_1 <- data.frame(Cancer=character(),
                                  Surrogate=character(),
                                  Analysis=character(),
                                  Ntrials=numeric(),
                                  Intercept=numeric(),
                                  Intercept_lb_ci=numeric(),
                                  Intercept_ub_ci=numeric(),
                                  Slope=numeric(),
                                  Slope_lb_ci=numeric(),
                                  Slope_ub_ci=numeric(),
                                  Correlation=numeric(),
                                  Correlation_lb_ci=numeric(),
                                  Correlation_ub_ci=numeric(),
                                  Rsquared=numeric(),
                                  Rsquared_lb_ci=numeric(),
                                  Rsquared_ub_ci=numeric()
                                  )

#function to print cancer-specific results
print_results <- function(results_surrogate_1, cancer) {
results_surrogate_1 %>%
  filter(Cancer==cancer)%>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()
}

#function for cancer-specific plots
plot_cancer <- function(finaldata_primary_1, cancer){
    
  plot_cancer <- ggplot(finaldata_primary_1, aes(x = exp(yi_s), y = exp(yi_m), label=trial_acro_sm, weight=weight_var)) +
    stat_smooth(method="lm", colour=NA, fullrange=T)+
    geom_point(aes(size = weight_var), shape = 16, colour="darkslateblue") +
    geom_abline(intercept = results_surrogate_1$Intercept[results_surrogate_1$Cancer==cancer], slope = results_surrogate_1$Slope[results_surrogate_1$Cancer==cancer]) +
    geom_abline(intercept=0, slope=1, linetype=2)+
    geom_hline(yintercept = 1, linetype=3)+
    geom_vline(xintercept = 1, linetype=3)+
    labs(x="RR late stage incidence", y="RR Mortality")+
    scale_x_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2)) + 
    scale_y_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2)) +
    geom_text(hjust=-0.05, vjust=-0.5)+
    theme_bw() +
    theme(legend.position = "none",plot.caption=element_text(hjust=0), aspect.ratio = 1)

    return(plot_cancer)

}


```

## Lung

```{r lung, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Lung.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  prep_data,
  analysis,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

#restrict to trials with surrogate timepoint before mortality timepoint
finaldata_primary_1 <- finaldata_primary_1 %>%
  filter(
    trial_acro_sm=="PLCO (Lung)" |
    trial_acro_sm=="UKLS" |
#      trial_acro_sm=="Lung Screening Study (LSS)" |
      trial_acro_sm=="ITALUNG" |
      trial_acro_sm=="Czech study" |
      trial_acro_sm=="LUSI")

finaldata_primary_1 <- prep_data(finaldata_primary_1)

results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Lung", "1. Absolute incidence of late stage cancer", "Subgroup", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Lung")

# bubble plot
plot_cancer(finaldata_primary_1,"Lung")

```

## Prostate

```{r prostate, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Prostate.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  prep_data,
  analysis,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

#restrict to trials with surrogate timepoint before mortality timepoint
finaldata_primary_1 <- finaldata_primary_1 %>%
  filter(
    trial_acro_sm=="UK CAP" |
      trial_acro_sm=="PLCO (Prostate)" |
      trial_acro_sm=="Norrkoping")

finaldata_primary_1 <- prep_data(finaldata_primary_1)

results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Prostate", "1. Absolute incidence of late stage cancer", "Subgroup", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Prostate")

# bubble plot
plot_cancer(finaldata_primary_1,"Prostate")

```

## Breast

```{r breast, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Breast.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  prep_data,
  analysis,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

#restrict to trials with surrogate timepoint before mortality timepoint
finaldata_primary_1 <- finaldata_primary_1 %>%
  filter(
    trial_acro_sm=="HIP" |
      trial_acro_sm=="Stockholm Breast" |
      trial_acro_sm=="Russia WHO Breast" )
#      trial_acro_sm=="Gothenburg Breast" |
#      trial_acro_sm=="UK Age")

finaldata_primary_1 <- prep_data(finaldata_primary_1)

results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Breast", "1. Absolute incidence of late stage cancer", "Subgroup", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Breast")

# bubble plot
plot_cancer(finaldata_primary_1,"Breast")


```

## Bowel

```{r bowel, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Bowel.R")

gdata::keep(
  finaldata_primary_1,
  results_surrogate_1,
  prep_data,
  analysis,
  print_results,
  plot_cancer,
  bootstrap_trial,
  sure = T
)

#restrict to trials with surrogate timepoint before mortality timepoint
finaldata_primary_1 <- finaldata_primary_1 %>%
  filter(
    trial_acro_sm=="SCORE" |
      trial_acro_sm=="Finnish RHS CRC" |
      trial_acro_sm=="NORCCAP" |
      trial_acro_sm=="Telemark Polyp I")

finaldata_primary_1 <- prep_data(finaldata_primary_1)

results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(finaldata_primary_1, "Bowel", "1. Absolute incidence of late stage cancer", "Subgroup", bootstrap_trial))

# print results table for cancer
print_results(results_surrogate_1, "Bowel")

# bubble plot
plot_cancer(finaldata_primary_1,"Bowel")

```


## All cancers
```{r all, echo=FALSE, warning=FALSE}

setwd("../code/Estimates")
source("Ovarian.R")
ovarian <- finaldata_primary_1 %>%
  mutate(cancer="Ovarian")

setwd("../code/Estimates")
source("Lung.R")
lung <- finaldata_primary_1 %>%
  mutate(cancer="Lung")

setwd("../code/Estimates")
source("Prostate.R")
prostate <- finaldata_primary_1 %>%
  mutate(cancer="Prostate")

setwd("../code/Estimates")
source("Breast.R")
breast <- finaldata_primary_1 %>%
  mutate(cancer="Breast")

setwd("../code/Estimates")
source("Bowel.R")
bowel <- finaldata_primary_1 %>%
  mutate(cancer="Bowel")

gdata::keep(
  ovarian,
  lung,
  prostate,
  breast,
  bowel,
  results_surrogate_1,
  analysis,
  prep_data,
  min_N_trials,
  bootstrap_trial,
  sure = T
)

all_finaldata_primary_1 <- bind_rows(ovarian,
                                     lung,
                                     prostate,
                                     breast,
                                     bowel)

#trials with surrogate timepoint < mortality timepoint (see 'word table.docx')
all_finaldata_primary_1 <- all_finaldata_primary_1 %>%
  filter(
    #ovarian
 #   trial_acro_sm=="UK Pilot Ovarian" |
    #lung
    trial_acro_sm=="PLCO (Lung)" |
    trial_acro_sm=="UKLS" |
#    trial_acro_sm=="Lung Screening Study (LSS)" |
    trial_acro_sm=="ITALUNG" |
    trial_acro_sm=="Czech study" |
    trial_acro_sm=="LUSI" |
    #prostate
    trial_acro_sm=="UK CAP" |
    trial_acro_sm=="PLCO (Prostate)" |
    trial_acro_sm=="Norrkoping" |
    #breast
    trial_acro_sm=="HIP" |
    trial_acro_sm=="Stockholm Breast" |
    trial_acro_sm=="Russia WHO Breast" |
  #  trial_acro_sm=="Gothenburg Breast" |
   # trial_acro_sm=="UK Age" |
    #bowel
    trial_acro_sm=="SCORE" |
    trial_acro_sm=="Finnish RHS CRC" |
    trial_acro_sm=="NORCCAP" |
    trial_acro_sm=="Telemark Polyp I")


all_finaldata_primary_1 <- prep_data(all_finaldata_primary_1)

results_surrogate_1 <- results_surrogate_1 %>%
  add_row(analysis(all_finaldata_primary_1, "All", "1. Absolute incidence of late stage cancer", "Subgroup", bootstrap_trial))

# print results table for all cancers
results_surrogate_1 %>%
  mutate(Slope_lb_ci=ifelse(Slope_lb_ci=="-99999","-Inf",Slope_lb_ci)) %>%
  mutate(Slope_ub_ci=ifelse(Slope_ub_ci=="99999","Inf",Slope_ub_ci)) %>%
  flextable() %>%
  set_header_labels(
    Ntrials = "N trials",
    Intercept_lb_ci="Intercept 95% CI; lower",
    Intercept_ub_ci="Intercept 95% CI; upper",
    Slope_lb_ci="Slope 95% CI; lower",
    Slope_ub_ci="Slope 95% CI; upper",
    Correlation_lb_ci="Correlation 95% CI; lower",
    Correlation_ub_ci="Correlation 95% CI; upper",
    Rsquared="R-squared",
    Rsquared_lb_ci="R-squared 95% CI; lower",
    Rsquared_ub_ci="R-squared 95% CI; upper") %>%
  autofit()

# bubble plot
ggplot(all_finaldata_primary_1, aes(x = exp(yi_s), y = exp(yi_m), weight=weight_var)) +
  stat_smooth(method="lm", colour=NA, fullrange=T)+
  geom_point(aes(size = weight_var, colour=cancer), shape = 16) + 
  geom_abline(data=results_surrogate_1, aes(intercept = Intercept[Cancer=="All"], slope = Slope[Cancer=="All"])) +
  geom_abline(intercept=0, slope=1, linetype=2)+
  geom_hline(yintercept = 1, linetype=3)+
  geom_vline(xintercept = 1, linetype=3)+
  scale_x_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2))+
  scale_y_continuous(trans="log", limits = c(0.3,2), breaks=c(0.5,1,1.5, 2))+
  labs(x="RR late stage incidence", y="RR Mortality")+
  theme_bw() +
  theme(plot.caption=element_text(hjust=0), aspect.ratio = 1) +
  guides(size = FALSE) 

```
